=== adalbertodev/anikisetsu/public/studios/studios.dtd
<!ELEMENT studios (studio+)>
<!ELEMENT studio (name, animes)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT animes (anime+)>
<!ELEMENT anime (title, score?, popularity?, year?, episodes?)>
<!ATTLIST anime
  id CDATA #REQUIRED
  format (MOVIE|ONA|ONE_SHOT|OVA|SPECIAL|TV|TV_SHORT) #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT popularity (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT episodes (#PCDATA)>

=== adalbertodev/anikisetsu/public/studios/studios.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studios SYSTEM "studios.dtd">
<?xml-stylesheet type="text/xsl" href="studios.xsl"?>

<studios>
  <studio>
    <name>TMS Entertainment</name>
    <animes>
      <anime id="199221" format="TV">
        <title>Dr. STONE: SCIENCE FUTURE Part 3</title>
        <score>81</score>
        <popularity>47622</popularity>
        <year>2026</year>
        <episodes>13</episodes>
      </anime>
      <anime id="199588" format="TV">
        <title>Otaku ni Yasashii Gal wa Inai!?</title>
        <score>74</score>
        <popularity>31502</popularity>
        <year>2026</year>
      </anime>
      <anime id="199029" format="ONA">
        <title>Kanojo, Okarishimasu 5th Season</title>
        <score>56</score>
        <popularity>13643</popularity>
        <year>2026</year>
        <episodes>12</episodes>
      </anime>
      <anime id="105333" format="TV">
        <title>Dr. STONE</title>
        <score>81</score>
        <popularity>517682</popularity>
        <year>2019</year>
        <episodes>24</episodes>
      </anime>
      <anime id="124194" format="TV">
        <title>Fruits Basket: The Final</title>
        <score>89</score>
        <popularity>167201</popularity>
        <year>2021</year>
        <episodes>13</episodes>
      </anime>
      <anime id="111762" format="TV">
        <title>Fruits Basket: 2nd Season</title>
        <score>85</score>
        <popularity>177424</popularity>
        <year>2020</year>
        <episodes>25</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>BUG FILMS</name>
    <animes>
      <anime id="147105" format="ONA">
        <title>Tongari Boushi no Atelier</title>
        <score>86</score>
        <popularity>115152</popularity>
        <year>2026</year>
        <episodes>13</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>Toei Animation</name>
    <animes>
      <anime id="21" format="TV">
        <title>ONE PIECE</title>
        <score>87</score>
        <popularity>686919</popularity>
        <year>1999</year>
      </anime>
      <anime id="197178" format="SPECIAL">
        <title>ONE PIECE HEROINES</title>
        <popularity>4819</popularity>
        <year>2026</year>
        <episodes>1</episodes>
      </anime>
      <anime id="182469" format="SPECIAL">
        <title>ONE PIECE FAN LETTER</title>
        <score>90</score>
        <popularity>50561</popularity>
        <year>2024</year>
        <episodes>1</episodes>
      </anime>
      <anime id="128207" format="MOVIE">
        <title>THE FIRST SLAM DUNK</title>
        <score>87</score>
        <popularity>29640</popularity>
        <year>2022</year>
        <episodes>1</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>Studio KAI</name>
    <animes>
      <anime id="186497" format="TV">
        <title>Koori no Jouheki</title>
        <score>76</score>
        <popularity>32121</popularity>
        <year>2026</year>
      </anime>
      <anime id="167152" format="TV">
        <title>Yuusha Kei ni Shosu: Choubatsu Yuusha 9004-tai Keimu Kiroku</title>
        <score>81</score>
        <popularity>125661</popularity>
        <year>2026</year>
        <episodes>12</episodes>
      </anime>
      <anime id="190704" format="TV">
        <title>Kanan-sama wa Akumade Choroi</title>
        <score>67</score>
        <popularity>25908</popularity>
        <year>2026</year>
        <episodes>12</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>Lerche</name>
    <animes>
      <anime id="180745" format="TV">
        <title>Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 4th Season 2-nensei-hen Ichi Gakki</title>
        <score>79</score>
        <popularity>73199</popularity>
        <year>2026</year>
        <episodes>16</episodes>
      </anime>
      <anime id="20755" format="TV">
        <title>Ansatsu Kyoushitsu</title>
        <score>79</score>
        <popularity>591848</popularity>
        <year>2015</year>
        <episodes>22</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>WHITE FOX</name>
    <animes>
      <anime id="189046" format="TV">
        <title>Re:Zero kara Hajimeru Isekai Seikatsu 4th Season</title>
        <score>87</score>
        <popularity>78233</popularity>
        <year>2026</year>
        <episodes>19</episodes>
      </anime>
      <anime id="21355" format="TV">
        <title>Re:Zero kara Hajimeru Isekai Seikatsu</title>
        <score>81</score>
        <popularity>570230</popularity>
        <year>2016</year>
        <episodes>25</episodes>
      </anime>
      <anime id="163134" format="TV">
        <title>Re:Zero kara Hajimeru Isekai Seikatsu 3rd Season</title>
        <score>84</score>
        <popularity>163993</popularity>
        <year>2024</year>
        <episodes>16</episodes>
      </anime>
      <anime id="9253" format="TV">
        <title>Steins;Gate</title>
        <score>89</score>
        <popularity>557292</popularity>
        <year>2011</year>
        <episodes>24</episodes>
      </anime>
      <anime id="20613" format="TV">
        <title>Akame ga Kill!</title>
        <score>73</score>
        <popularity>506414</popularity>
        <year>2014</year>
        <episodes>24</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>Jumondou</name>
    <animes>
      <anime id="182483" format="TV">
        <title>Hime Kishi wa Barbaroi no Yome</title>
        <score>66</score>
        <popularity>28211</popularity>
        <year>2026</year>
        <episodes>12</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>bones film</name>
    <animes>
      <anime id="199547" format="TV">
        <title>MARRIAGETOXIN</title>
        <score>75</score>
        <popularity>41693</popularity>
        <year>2026</year>
      </anime>
      <anime id="195600" format="TV">
        <title>Yomi no Tsugai</title>
        <score>78</score>
        <popularity>68598</popularity>
        <year>2026</year>
        <episodes>24</episodes>
      </anime>
      <anime id="178025" format="TV">
        <title>Gachiakuta</title>
        <score>82</score>
        <popularity>206668</popularity>
        <year>2025</year>
        <episodes>24</episodes>
      </anime>
      <anime id="204356" format="SPECIAL">
        <title>Boku no Hero Academia No. 170+1: More</title>
        <popularity>19387</popularity>
        <year>2026</year>
        <episodes>1</episodes>
      </anime>
      <anime id="182896" format="TV">
        <title>Boku no Hero Academia FINAL SEASON</title>
        <score>87</score>
        <popularity>107493</popularity>
        <year>2025</year>
        <episodes>11</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>studio A-CAT</name>
    <animes>
      <anime id="194317" format="TV">
        <title>Saikyou no Ousama, Nidome no Jinsei wa Nani wo Suru? 2nd Season</title>
        <score>54</score>
        <popularity>28475</popularity>
        <year>2026</year>
        <episodes>12</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>Studio Comet</name>
    <animes>
      <anime id="195333" format="TV">
        <title>Haibara-kun no Tsuyokute Seishun New Game</title>
        <score>63</score>
        <popularity>13066</popularity>
        <year>2026</year>
        <episodes>12</episodes>
      </anime>
      <anime id="199408" format="TV">
        <title>Buchigire Reijou wa Houfuku wo Chikaimashita.: Madousho no Chikara de Sokoku wo
          Tataki Tsubushimasu</title>
        <popularity>2487</popularity>
        <year>2026</year>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>CONNECT</name>
    <animes>
      <anime id="169580" format="TV">
        <title>Class de 2-banme ni Kawaii Onnanoko to Tomodachi ni Natta</title>
        <score>76</score>
        <popularity>38154</popularity>
        <year>2026</year>
        <episodes>12</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>Actas</name>
    <animes>
      <anime id="182300" format="TV">
        <title>Tsue to Tsurugi no Wistoria Season 2</title>
        <score>80</score>
        <popularity>57885</popularity>
        <year>2026</year>
      </anime>
      <anime id="174576" format="TV">
        <title>Tsue to Tsurugi no Wistoria</title>
        <score>78</score>
        <popularity>133396</popularity>
        <year>2024</year>
        <episodes>12</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>BENTEN Film</name>
    <animes>
      <anime id="179950" format="TV">
        <title>Reincarnation no Kaben</title>
        <score>60</score>
        <popularity>21440</popularity>
        <year>2026</year>
        <episodes>13</episodes>
      </anime>
    </animes>
  </studio>
  <studio>
    <name>MAPPA</name>
    <animes>
      <anime id="172463" format="TV">
        <title>Jujutsu Kaisen: Shimetsu Kaiyuu - Zenpen</title>
        <score>86</score>
        <popularity>202033</popularity>
        <year>2026</year>
        <episodes>12</episodes>
      </anime>
      <anime id="173172" format="ONA">
        <title>Dorohedoro Season 2</title>
        <score>80</score>
        <popularity>30928</popularity>
        <year>2026</year>
        <episodes>11</episodes>
      </anime>
      <anime id="166613" format="TV">
        <title>Jigokuraku 2nd Season</title>
        <score>82</score>
        <popularity>139475</popularity>
        <year>2026</year>
        <episodes>12</episodes>
      </anime>
      <anime id="113415" format="TV">
        <title>Jujutsu Kaisen</title>
        <score>84</score>
        <popularity>896539</popularity>
        <year>2020</year>
        <episodes>24</episodes>
      </anime>
      <anime id="171627" format="MOVIE">
        <title>Chainsaw Man: Reze-hen</title>
        <score>90</score>
        <popularity>185006</popularity>
        <year>2025</year>
        <episodes>1</episodes>
      </anime>
